services:
  - type: web
    name: projeto-museu
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn projeto_museu.wsgi
    staticPublishPath: staticfiles
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: projeto_museu.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
