# Generated by Django 5.1.3 on 2025-06-27 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(default='', max_length=15)),
                ('tipo_visitante', models.CharField(choices=[('individual', 'Individual'), ('grupo', 'Grupo de Amigos'), ('instituicao', 'Instituição')], default='individual', max_length=20)),
                ('instituicao', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade_visitantes', models.PositiveIntegerField(default=1)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
