# Generated by Django 5.1.3 on 2025-01-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sobrenome', models.CharField(max_length=150)),
                ('email', models.EmailField(default='visitante@example.com', max_length=254)),
                ('telefone', models.CharField(default='(00) 00000-0000', max_length=15)),
                ('tipo_visitante', models.CharField(choices=[('individual', 'Individual'), ('instituicao', 'Instituição')], default='individual', max_length=20)),
                ('instituicao', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sobrenome', models.CharField(max_length=150)),
                ('email', models.EmailField(default='@example.com', max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
    ]
