# Generated by Django 5.1.3 on 2024-12-07 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroUsuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=255, unique=True)),
                ('email_usuario', models.CharField(max_length=255, unique=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('senha_usuario', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='LoginUsuario',
            fields=[
                ('id_login', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=25)),
                ('senha_usuario', models.CharField(max_length=15)),
                ('data_login', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Sucesso', 'Sucesso'), ('Falha', 'Falha')], max_length=50)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.cadastrousuario')),
            ],
        ),
    ]
